spring.application.name=ApiFacturacion
server.port=8092

spring.datasource.url=jdbc:sqlite:C:/sqlite/facturacion.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
springdoc.default-produces-media-type=application/vnd.api+json
springdoc.default-consumes-media-type=application/vnd.api+json

# API URls
apis.producto.url=http://localhost:8081/api/productos
apis.inventario.url=http://localhost:8082/api/inventarios

# Config de timeouts y reintentos
restclient.connect-timeout=2000
restclient.read-timeout=5000
restclient.max-retries=3