spring.application.name=ApiInventarios
server.port=8091

spring.datasource.url=jdbc:sqlite:C:/sqlite/inventorysdb.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
springdoc.default-produces-media-type=application/vnd.api+json
springdoc.default-consumes-media-type=application/vnd.api+json

security.api.key=INV-654321